import { NextResponse } from "next/server"

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 600))

  // Mock AI news posts - in production, these would be generated by AI or fetched from news APIs
  const newsPosts = [
    {
      id: "1",
      title: "AI Breakthrough: New Language Model Achieves Human-Level Reasoning",
      category: "AI",
      content:
        "Researchers at leading tech companies have developed a revolutionary AI system that demonstrates unprecedented reasoning capabilities, potentially transforming how we interact with artificial intelligence.",
      backgroundColor: "from-blue-600 to-purple-700",
      textColor: "text-white",
      accentColor: "text-blue-200",
      timestamp: "2 hours ago",
    },
    {
      id: "2",
      title: "The Future of Remote Work: Virtual Reality Offices",
      category: "Tech",
      content:
        "Companies are increasingly adopting VR technology to create immersive remote work environments, offering employees the benefits of in-person collaboration from anywhere in the world.",
      backgroundColor: "from-emerald-500 to-teal-600",
      textColor: "text-white",
      accentColor: "text-emerald-200",
      timestamp: "4 hours ago",
    },
    {
      id: "3",
      title: "Mindful Productivity: The Science Behind Focus",
      category: "Motivation",
      content:
        "New research reveals how mindfulness practices can dramatically improve focus and productivity, with simple techniques that can be implemented in just 5 minutes a day.",
      backgroundColor: "from-orange-500 to-red-600",
      textColor: "text-white",
      accentColor: "text-orange-200",
      timestamp: "6 hours ago",
    },
    {
      id: "4",
      title: "Sustainable Cooking: Plant-Based Innovations",
      category: "Lifestyle",
      content:
        "Discover the latest plant-based cooking innovations that are revolutionizing sustainable eating, from lab-grown ingredients to zero-waste cooking techniques.",
      backgroundColor: "from-green-600 to-lime-600",
      textColor: "text-white",
      accentColor: "text-green-200",
      timestamp: "8 hours ago",
    },
  ]

  return NextResponse.json({
    posts: newsPosts,
    total: newsPosts.length,
  })
}
